[[chap_02]]
Writing and debugging scripts
-----------------------------

______________________________________________________
After going through this chapter, you will be able to:

* Write a simple script
* Define the shell type that should execute the script
* Put comments in a script
* Change permissions on a script
* Execute and debug a script
______________________________________________________

[[sect_02_01]]
Creating and running a script
-----------------------------

[[sect_02_01_01]]
Writing and naming
~~~~~~~~~~~~~~~~~~

A shell script is a sequence of commands for which you have a repeated
use. This sequence is typically executed by entering the name of the
script on the command line. Alternatively, you can use scripts to
automate tasks using the cron facility. Another use for scripts is in
the UNIX boot and shutdown procedure, where operation of daemons and
services are defined in init scripts.

To createscriptscreation a shell script, open a new empty file in your
editor. Any text editor will do: `vim`, `emacs`, `gedit`, `dtpad` et
cetera are all valid. You might want to chose a more advanced editor
like `vim` or `emacs`, however, because these can be configured to
recognize shell and Bash syntax and can be a great help in preventing
those errors that beginners frequently make, such as forgetting brackets
and semi-colons.

____________________________________________________________________
*Tip*

In order to activate syntax highlighting in `vim`, use the command

:syntax enable

or

:sy enable

or

:syn enable

You can add this setting to your `.vimrc` file to make it permanent.
____________________________________________________________________

Put UNIX commands in the new empty file, like you would enter them on
the command line. As discussed in the previous chapter (see
link:#sect_01_03[???]), commands can be shell functions, shell
built-ins, UNIX commands and other scripts.

Give your script a sensible namescriptsnaming that gives a hint about
what the script does. Make sure that your script name does not conflict
with existing commands. In order to ensure that no confusion can rise,
script names often end in `.sh`; even so, there might be other scripts
on your system with the same name as the one you chose. Check using
`which`, `whereis` and other commands for finding information about
programs and files:

which

-a

script_name

whereis

script_name

locate

script_name

[[sect_02_01_02]]
script1.sh
~~~~~~~~~~

In this examplescriptsexample we use the `echo` Bash built-in to inform
the user about what is going to happen, before the task that will create
the output is executed. It is strongly advised to inform users about
what a script is doing, in order to prevent them from becoming nervous
_because the script is not doing anything_. We will return to the
subject of notifying users in link:#chap_08[???].

image:images/script1.sh.eps[script1.sh]

Write this script for yourself as well. It might be a good idea to
create a directory `~/scripts` to hold your scripts. Add the directory
to the contents of the `PATH` variablevariablesPATH:

export

PATH

="

$PATH

:

~/scripts

"

If you are just getting started with Bash, use a text editor that uses
different colours for different shell constructs. Syntax highlighting is
supported by `vim`, `gvim`, `(x)emacs`, `kwrite` and many other editors;
check the documentation of your favorite editor.

___________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
*Note*

The prompts throughout this course vary depending on the author's mood.
This resembles much more real life situations than the standard
educational _$_ prompt. The only convention we stick to, is that the
_root_ prompt ends in a hash mark (#).
___________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

[[sect_02_01_03]]
Executing the script
~~~~~~~~~~~~~~~~~~~~

The script should have executescriptsexecution permissions for the
correct owners in order to be runnable. When setting
permissionsscriptspermissions, check that you really obtained the
permissions that you want. When this is done, the script can run like
any other command:

....
willy:~/scripts> chmod u+x script1.sh

willy:~/scripts> ls -l script1.sh
-rwxrw-r--    1 willy   willy       456 Dec 24 17:11 script1.sh

willy:~> script1.sh
The script starts now.
Hi, willy!

I will now fetch you a list of connected users:

  3:38pm  up 18 days,  5:37,  4 users,  load average: 0.12, 0.22, 0.15
USER     TTY      FROM              LOGIN@   IDLE   JCPU   PCPU  WHAT
root     tty2     -                Sat 2pm  4:25m  0.24s  0.05s  -bash
willy    :0       -                Sat 2pm   ?     0.00s   ?     -
willy    pts/3    -                Sat 2pm  3:33m 36.39s 36.39s  BitchX willy ir
willy    pts/2    -                Sat 2pm  3:33m  0.13s  0.06s  /usr/bin/screen

I'm setting two variables now.
This is a string: black
And this is a number: 9

I'm giving you back your prompt now.

willy:~/scripts> echo $COLOUR

willy:~/scripts> echo $VALUE

willy:~/scripts>
....

This is the most common way to execute a script. It is preferred to
execute the script like this in a subshell. The variables, functions and
aliases created in this subshell are only known to the particular bash
session of that subshell. When that shell exits and the parent regains
control, everything is cleaned up and all changes to the state of the
shell made by the script, are forgotten.

If you did not put the `scripts` directory in your `PATH`, and `.` (the
current directory) is not in the `PATH` either, you can activate the
script like this:

./script_name.sh

A script can also explicitly be executed by a given shell, but generally
we only do this if we want to obtain special behavior, such as checking
if the script works with another shell or printing traces for debugging:

rbash

script_name.sh

sh

script_name.sh

bash

-x

script_name.sh

The specified shell will start as a subshell of your current shell and
execute the script. This is done when you want the script to start up
with specific options or under specific conditions which are not
specified in the script.

If you don't want to start a new shell but execute the script in the
current shell, you _sourcebuilt-inssource_ it:

source

script_name.sh

_______________________________________________________________________________
*Tip*

The Bash `source` built-in is a synonym for the Bourne shell `.` (dot)
command.
_______________________________________________________________________________

The script does not need execute permission in this case. Commands are
executed in the current shell context, so any changes made to your
environment will be visible when the script finishes execution:

....
willy:~/scripts> source script1.sh
--output ommitted--

willy:~/scripts> echo $VALUE
9

willy:~/scripts>
....

[[sect_02_02]]
Script basics
-------------

[[sect_02_02_01]]
Which shell will run the script?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

When running a script in a subshellscriptsexecuting shell, you should
define which shell should run the script. The shell type in which you
wrote the script might not be the default on your system, so commands
you entered might result in errors when executed by the wrong shell.

The first line of the script determines the shell to start. The first
two characters of the first line should be _#!_, then follows the path
to the shell that should interpret the commands that follow. Blank lines
are also considered to be lines, so don't start your script with an
empty line.

For the purpose of this course, all scripts will start with the line

#!/bin/bash

As noted before, this implies that the Bash executable can be found in
`/bin`.

[[sect_02_02_02]]
Adding comments
~~~~~~~~~~~~~~~

You should be aware of the fact that you might not be the only person
reading your code. A lot of users and system administrators run scripts
that were written by other people. If they want to see how you did it,
commentsscriptscomments are useful to enlighten the reader.

Commentscommentsusage also make your own life easier. Say that you had
to read a lot of man pages in order to achieve a particular result with
some command that you used in your script. You won't remember how it
worked if you need to change your script after a few weeks or months,
unless you have commented what you did, how you did it and/or why you
did it.

Take the `script1.sh` example and copy it to `commented-script1.sh`,
which we edit so that the comments reflect what the script does.
Everything the shell encounters after a hash mark on a line is ignored
and only visible upon opening the shell script file:

....
#!/bin/bash
# This script clears the terminal, displays a greeting and gives information
# about currently connected users.  The two example variables are set and displayed.

clear               # clear terminal window

echo "The script starts now."

echo "Hi, $USER!"       # dollar sign is used to get content of variable
echo

echo "I will now fetch you a list of connected users:"
echo                            
w               # show who is logged on and
echo                # what they are doing

echo "I'm setting two variables now."
COLOUR="black"                  # set a local shell variable
VALUE="9"                   # set a local shell variable
echo "This is a string: $COLOUR"        # display content of variable 
echo "And this is a number: $VALUE"     # display content of variable
echo

echo "I'm giving you back your prompt now."
echo
....

In a decent script, the first lines are usually comment about what to
expect. Then each big chunk of commands will be commented as needed for
clarity's sake. Linux init scripts, as an example, in your system's
`init.d` directory, are usually well commented since they have to be
readable and editable by everyone running Linux.

[[sect_02_03]]
Debugging Bash scripts
----------------------

[[sect_02_03_01]]
Debugging on the entire script
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

When thingsscriptsdebugging don't go according to plan, you need to
determine what exactly causes the script to fail. Bash provides
extensive debuggingdebugging features. The most common is to start up
the subshell with the `-x` option, which will run the entire script in
debug mode. Traces of each command plus its arguments are printed to
standard output after the commands have been expanded but before they
are executed.

This is the `commented-script1.sh` script ran in debug modedebuggingon
entire script. Note again that the added comments are not visible in the
output of the script.

....
willy:~/scripts> bash -x script1.sh
+ clear

+ echo 'The script starts now.'
The script starts now.
+ echo 'Hi, willy!'
Hi, willy!
+ echo

+ echo 'I will now fetch you a list of connected users:'
I will now fetch you a list of connected users:
+ echo

+ w
  4:50pm  up 18 days,  6:49,  4 users,  load average: 0.58, 0.62, 0.40
USER     TTY      FROM              LOGIN@   IDLE   JCPU   PCPU  WHAT
root     tty2     -                Sat 2pm  5:36m  0.24s  0.05s  -bash
willy    :0       -                Sat 2pm   ?     0.00s   ?     -
willy    pts/3    -                Sat 2pm 43:13  36.82s 36.82s  BitchX willy ir
willy    pts/2    -                Sat 2pm 43:13   0.13s  0.06s  /usr/bin/screen
+ echo

+ echo 'I'\''m setting two variables now.'
I'm setting two variables now.
+ COLOUR=black
+ VALUE=9
+ echo 'This is a string: '
This is a string:
+ echo 'And this is a number: '
And this is a number:
+ echo

+ echo 'I'\''m giving you back your prompt now.'
I'm giving you back your prompt now.
+ echo
....

There is now a full-fledged debugger for Bash, available at
http://bashdb.sourceforge.net[SourceForge]. These debugging features are
available in most modern versions of Bash, starting from 3.x.

[[sect_02_03_02]]
Debugging on part(s) of the script
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Using the `set` Bash built-in you can run in normal mode those
portionsdebuggingpartial of the script of which you are sure they are
without fault, and display debugging information only for troublesome
zones. Say we are not sure what the `w` command will do in the example
`commented-script1.sh`, then we could enclose it in the script like
this:

....
set -x          # activate debugging from here
w
set +x          # stop debugging from here
....

Output then looks like this:

....
willy: ~/scripts> script1.sh
The script starts now.
Hi, willy!

I will now fetch you a list of connected users:

+ w
  5:00pm  up 18 days,  7:00,  4 users,  load average: 0.79, 0.39, 0.33
USER     TTY      FROM              LOGIN@   IDLE   JCPU   PCPU  WHAT
root     tty2     -                Sat 2pm  5:47m  0.24s  0.05s  -bash
willy    :0       -                Sat 2pm   ?     0.00s   ?     -
willy    pts/3    -                Sat 2pm 54:02  36.88s 36.88s  BitchX willyke
willy    pts/2    -                Sat 2pm 54:02   0.13s  0.06s  /usr/bin/screen
+ set +x

I'm setting two variables now.
This is a string:
And this is a number:

I'm giving you back your prompt now.

willy: ~/scripts>
....

You can switch debugging mode on and off as many times as you want
within the same script.

The table below gives an overview of other useful Bash
optionsdebuggingoptions:

.Overview of set debugging options
[cols=",,",options="header",]
|=======================================================================
|Short notation |Long notation |Result
|set -f |set -o noglob |Disable file name generation using
metacharacters (globbing).

|set -v |set -o verbose |Prints shell input lines as they are read.

|set -x |set -o xtrace |Print command traces before executing command.
|=======================================================================

The dash is used to activate a shell option and a plus to deactivate it.
Don't let this confuse you!

In the example below, we demonstrate these options on the command line:

....
willy:~/scripts> set -v

willy:~/scripts> ls
ls 
commented-scripts.sh    script1.sh

willy:~/scripts> set +v
set +v

willy:~/scripts> ls *
commented-scripts.sh    script1.sh

willy:~/scripts> set -f

willy:~/scripts> ls *
ls: *: No such file or directory

willy:~/scripts> touch *

willy:~/scripts> ls
*   commented-scripts.sh    script1.sh

willy:~/scripts> rm *

willy:~/scripts> ls
commented-scripts.sh    script1.sh
....

Alternatively, these modes can be specified in the script itself, by
adding the desired options to the first line shell declaration. Options
can be combined, as is usually the case with UNIX commands:

#!/bin/bash

-xv

Once you found the buggydebuggingecho statements part of your script,
you can add `echo` statements before each command of which you are
unsure, so that you will see exactly where and why things don't work. In
the example `commented-script1.sh` script, it could be done like this,
still assuming that the displaying of users gives us problems:

....
echo "debug message: now attempting to start w command"; w
....

In more advanced scripts, the `echo` can be inserted to display the
content of variables at different stages in the script, so that flaws
can be detected:

....
echo "Variable VARNAME is now set to $VARNAME."
....

[[sect_02_05]]
Summary
-------

A shell script is a reusable series of commands put in an executable
text file. Any text editor can be used to write scripts.

Scripts start with _#!_ followed by the path to the shell executing the
commands from the script. Comments are added to a script for your own
future reference, and also to make it understandable for other users. It
is better to have too many explanations than not enough.

Debugging a script can be done using shell options. Shell options can be
used for partial debugging or for analyzing the entire script. Inserting
`echo` commands at strategic locations is also a common troubleshooting
technique.

[[sect_02_06]]
Exercises
---------

This exercise will help you to create your first script.

1.  Write a script using your favorite editor. The script should display
the path to your homedirectory and the terminal type that you are using.
Additionally it shows all the services started up in runlevel 3 on your
system. (hint: use `HOME`, `TERM` and `ls /etc/rc3.d/S*`)
2.  Add comments in your script.
3.  Add information for the users of your script.
4.  Change permissions on your script so that you can run it.
5.  Run the script in normal mode and in debug mode. It should run
without errors.
6.  Make errors in your script: see what happens if you misspell
commands, if you leave out the first line or put something
unintelligible there, or if you misspell shell variable names or write
them in lower case characters after they have been declared in capitals.
Check what the debug comments say about this.
